databaseChangeLog:
  - changeSet:
      id: 20200324-93
      author: akurutin (generated)
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: user_settings_pkey
                  name: id
                  type: BIGINT
              - column:
                  name: key
                  type: VARCHAR(255)
              - column:
                  name: data
                  type: TEXT
            tableName: user_settings